### ISSUE TITLE
Hold up

### ISSUE THREAD

**Issue by jeydinpham** [Tomato6966/discord-music-bot#4]
You got Spotify to work with DisTube?

**Comment by Tomato6966** [comment]
Yeah ofc. Later i will also cover playlist support

**Comment by Tomato6966** [comment]
Episode 9 will be seek forward and rewind
Episode 10 will be now playing with a bar creation
Episode 11 will cover filters
Episode 12 lyrics
Episode 13 searching with youtube
Episode 14 searching with soundcloud
Episode 15 reactions
Episode 16 spotify playlist
Episode 17 handy distube settings
Episode 18 cookies
Episode 19...

Maybe sometime i will add request feature channel (like #distube-music)

**Comment by jeydinpham** [comment]
Wowo ima give a sub

**Comment by jeydinpham** [comment]
![Screen Shot 2021-03-01 at 6 34 02 PM](https://user-images.githubusercontent.com/62669147/109578421-c1df2880-7abc-11eb-9b8b-91c2147b398c.png)
Wowo this happened when I added a Spotify playlist link, very kewl

**Comment by jeydinpham** [comment]
Are you gonna consider custom playlists o.O

**Comment by Tomato6966** [comment]
Yea
